In [ ]:
a=[5,73,8,29,10]
print(sorted(a))

[5, 8, 10, 29, 73]


In [ ]:
a=[5,73,8,29,10]
b=sorted(a)
print(b)

[5, 8, 10, 29, 73]


In [ ]:
import numpy as np
A=np.arange(1,13).reshape(4,3)
print(A)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
import numpy as np
A=np.linspace(4,9,12).reshape(3,4)
print(A)

[[4.         4.45454545 4.90909091 5.36363636]
 [5.81818182 6.27272727 6.72727273 7.18181818]
 [7.63636364 8.09090909 8.54545455 9.        ]]


In [ ]:
A=np.array([45,87,68,90,43,21,76,80]).reshape(2,2,2)
print(A)

[[[45 87]
  [68 90]]

 [[43 21]
  [76 80]]]


In [ ]:
A=np.array([45,87,68,90,43,21,76,80])
A.resize(2,2,2)#changes the shape of original arraay
print(A)

[[[45 87]
  [68 90]]

 [[43 21]
  [76 80]]]


In [ ]:
A=np.array([34,56,45,48,90])
B=np.array([4,5,8,9,1])#list will throw an error while arrays iterate themselves
C=A-B
print(C)

[30 51 37 39 89]


In [ ]:
A=np.array([34,56,45,48,90])
B=np.array([4,5,8,9,1])#list will throw an error while arrays iterate themselves
C=A+B
print(C)

[38 61 53 57 91]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)#one one on multiplication
C=A*B
print(C)
print(A)
print(B)

[[136 280]
 [360 810]]
[[34 56]
 [45 90]]
[[4 5]
 [8 9]]


In [ ]:
A=np.array([34.2,56.7,78.2,90.9,90.8])
print(A.max())
print(A.min())

90.9
34.2


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)#list will throw an error while arrays iterate themselves
C=A@B#matrix multiplication
print(C)
print(A)
print(B)

[[ 584  674]
 [ 900 1035]]
[[34 56]
 [45 90]]
[[4 5]
 [8 9]]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)#list will throw an error while arrays iterate themselves
C=A.dot(B)#matrix multiplication
print(C)
print(A)
print(B)

[[ 584  674]
 [ 900 1035]]
[[34 56]
 [45 90]]
[[4 5]
 [8 9]]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
print(A)
print(A.max(axis=0))#axis 0-column
print("    ")
print(A.max(axis=1))#axis 1-column


[[34 56]
 [45 90]]
[45 90]
    
[56 90]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)
print(A)
print("____________________")
print(B)
print("After vertically stacking the arrays!")
print(np.vstack((A,B)))

[[34 56]
 [45 90]]
____________________
[[4 5]
 [8 9]]
After vertically stacking the arrays!
[[34 56]
 [45 90]
 [ 4  5]
 [ 8  9]]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)
print(A)
print("____________________")
print(B)
print("After horizontally stacking the arrays!")
print(np.hstack((A,B)))

[[34 56]
 [45 90]]
____________________
[[4 5]
 [8 9]]
After horizontally stacking the arrays!
[[34 56  4  5]
 [45 90  8  9]]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)
print(A)
print("____________________")
print(B)
print("After stacking the arrays!")
print(np.stack((A,B),axis=0))

[[34 56]
 [45 90]]
____________________
[[4 5]
 [8 9]]
After vertically stacking the arrays!
[[[34 56]
  [45 90]]

 [[ 4  5]
  [ 8  9]]]


In [ ]:
A=np.array([34,56,45,90]).reshape(2,2)
B=np.array([4,5,8,9]).reshape(2,2)
print(A)
print("____________________")
print(B)
print("After stacking the arrays!")
print(np.stack((A,B),axis=1))

[[34 56]
 [45 90]]
____________________
[[4 5]
 [8 9]]
After stacking the arrays!
[[[34 56]
  [ 4  5]]

 [[45 90]
  [ 8  9]]]


In [ ]:
A=np.arange(30).reshape(2,3,5)
print(A)
print("After dstack")
print(np.dstack(A))#no of rows-->no.of grps
#no.of col in every grp-->no.of rows in every grp
#[0,0],[1,1]...............

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]
After dstack
[[[ 0 15]
  [ 1 16]
  [ 2 17]
  [ 3 18]
  [ 4 19]]

 [[ 5 20]
  [ 6 21]
  [ 7 22]
  [ 8 23]
  [ 9 24]]

 [[10 25]
  [11 26]
  [12 27]
  [13 28]
  [14 29]]]


In [ ]:
#splitting arrays
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
print(np.vsplit(A,3))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11]]), array([[12, 13, 14],
       [15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
print(np.vsplit(A,(2,5)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]]), array([[15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
print(np.vsplit(A,(2,3)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[0, 1, 2],
       [3, 4, 5]]), array([[6, 7, 8]]), array([[ 9, 10, 11],
       [12, 13, 14],
       [15, 16, 17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print("After splitting")
print(np.hsplit(A,3))#here 3 indicates grp

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
After splitting
[array([[ 0],
       [ 3],
       [ 6],
       [ 9],
       [12],
       [15]]), array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]])]


In [ ]:
A=np.arange(18).reshape(3,6)
print(A)
print("After splitting")
print(np.hsplit(A,(2,5)))

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]]
After splitting
[array([[ 0,  1],
       [ 6,  7],
       [12, 13]]), array([[ 2,  3,  4],
       [ 8,  9, 10],
       [14, 15, 16]]), array([[ 5],
       [11],
       [17]])]


In [ ]:
A=np.arange(18).reshape(6,3)
print(A)
print(A.argmax())#maximum element position

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
17


In [ ]:
A=np.array([12,13,141,15,16,161,17,18]).reshape(2,4)
print(A)
print(A.argmax(axis=0))#[0 0 0
                       # 1 1 1
                       # 2 2 2]

[[ 12  13 141  15]
 [ 16 161  17  18]]
[1 1 0 1]


In [ ]:
A=np.array([12,13,141,15,16,161,17,18]).reshape(2,4)
print(A)
print(A.argmin(axis=0))
A=np.array([12,13,141,15,16,161,17,18]).reshape(2,4)
print(A)
print(A.argmax(axis=1))



[[ 12  13 141  15]
 [ 16 161  17  18]]
[0 0 1 0]
[[ 12  13 141  15]
 [ 16 161  17  18]]
[2 1]


STATISTICS

In [ ]:
#MEAN,MEDIAN,STD,VAR
A=np.array([12,34,25,66,71,88])
print("mean:",np.mean(A))
print("median:",np.median(A))
print("variance:",np.var(A))
print("standard dev:",np.std(A))

mean: 49.333333333333336
median: 50.0
variance: 743.888888888889
standard dev: 27.274326552435515


TRIGONOMETRY

In [ ]:
A=np.pi
print(A)

3.141592653589793


In [ ]:
A=np.array([np.pi/4,np.pi/6,np.pi/2,np.pi])
print(A)

[0.78539816 0.52359878 1.57079633 3.14159265]


In [ ]:
np.rad2deg(A)#rad to degree

array([ 45.,  30.,  90., 180.])

In [ ]:
np.rad2deg(A)


180.0

In [ ]:
c=np.array([0,30,23,45,65])
D=np.deg2rad(c)
print(D)

[0.         0.52359878 0.40142573 0.78539816 1.13446401]


In [ ]:
np.sin(c)

array([ 0.        , -0.98803162, -0.8462204 ,  0.82682868])

In [ ]:
np.cos(c)

array([ 1.        ,  0.15425145, -0.53283302, -0.56245385])

In [ ]:
np.tan(c)

array([ 0.        , -6.4053312 ,  1.58815308,  1.61977519, -1.47003826])

In [ ]:
np.arcsin(1)#sin^-1

1.5707963267948966

In [ ]:
np.arctan(1)#tan^-1

0.7853981633974483

In [ ]:
np.arccos(1)#cos^-1

0.0

In [ ]:
a=6
b=8
print(np.hypot(a,b))

10.0


SEARCHING!

In [ ]:
A=np.array([90,3,45,74,32])
print(np.where(A==74))

(array([3]),)


In [ ]:
A=np.array([90,3,45,74,32])
print(np.where(A%2==0))

(array([0, 3, 4]),)


In [ ]:
A=np.array([90,3,45,74,32])
print(np.where(A<74))

(array([1, 2, 4]),)


In [ ]:
#create an array
A=np.array([3,45,74,90])#outputs the index of a sorted element!
print(np.searchsorted(A,45))
#3,32,45,74,90

1


LINEAR ALGEBRA AND UFUNC

In [ ]:
A=np.array([6,24,60,48,46])
B=np.array([3,1,5,9,4])
print(np.add(A,B))
print(np.subtract(A,B))

[ 9 25 65 57 50]
[ 3 23 55 39 42]


In [ ]:
print(np.divide(A,B))#quotient
print(np.mod(A,B))#remainder
print(np.divmod(A,B))#both qut and remainder

[ 2.         24.         12.          5.33333333 11.5       ]
[0 0 0 3 2]
(array([ 2, 24, 12,  5, 11]), array([0, 0, 0, 3, 2]))


In [ ]:
a=np.array([6,24,60,12,18])#sort the elements
print(np.sort(A))

[ 6 24 46 48 60]


In [ ]:
a=np.array([6,24,60,45,18])
print(np.diff(a))

[ 18  36 -15 -27]


SET FUNCTIONS

In [ ]:
a=np.array([6,24,60,12,18])
a=np.array([5,4,6,2,1])
print(np.union1d(A,B))

[ 1  3  4  5  6  9 24 46 48 60]


In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([5,4,6,2,1])
print(np.setdiff1d(a,b))

[12 18 24 60]


In [ ]:
a=np.array([6,24,60,12,18])
b=np.array([5,4,6,2,1])
print(np.intersect1d(a,b))

[6]


ROUNDING

In [ ]:
a=np.trunc([-3.156,3.667])
print(a)


[-3.  3.]


In [ ]:
a=np.fix([-3.156,3.667])
print(a)#similar to trunc

[-3.  3.]


In [ ]:
a=np.floor([-8.6856,9.8537])
print(a)

[-9.  9.]


In [ ]:
a=np.ceil([-8.6856,9.8537])
print(a)

[-8. 10.]


In [ ]:
a=np.around([-81.56,12.57])
print(a)

[-82.  13.]


MORE FUNCTIONS

In [ ]:
a=np.array([1,2,3,4,5])
print(np.cumsum(a))


[ 1  3  6 10 15]


In [ ]:
a=np.array([1,2,3,4,5])
print(np.cumprod(a))
print(np.lcm(24,64))

[  1   2   6  24 120]
192


In [ ]:
print(np.gcd(24,64))
print(np.lcm(24,64))

8
192


In [ ]:
A=np.array([45,64,12])
print(np.lcm.reduce(A))

2880


In [ ]:
A=np.array([45,64,12])
print(np.gcd.reduce(A))

1


In [ ]:
A=np.array([[45,64],[1,2]])
print(np.linalg.inv(A))#A^-1

[[ 0.07692308 -2.46153846]
 [-0.03846154  1.73076923]]


RANDOM

In [ ]:
from numpy import random as rd
A=rd.rand()
print(A)


0.8237908205131355


In [ ]:
A=rd.rand(10)#n #default limit 0 to 0.99
print(A)

[0.05689157 0.64237969 0.86383636 0.96302632 0.38772501 0.72544888
 0.58074652 0.67943664 0.12175992 0.95603354]


In [ ]:
A=rd.randint(4)# randint(limit)==>limit 0,1,2,3,4
print(A)

2


In [ ]:
A=rd.randint(80,size=6)#limit,size
print(A)#limit gives random number from the 80

[35  1 65 55 22 51]


In [ ]:
A=rd.randint(80,size=(6,2))
print(A)

[[29 61]
 [ 4 54]
 [43 48]
 [43 43]
 [34 35]
 [16 21]]


JOINS

In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.inner(A,B))#1*4 + 2*5 + 3*6

32


In [ ]:
A=np.array([1,2,3])
B=np.array([4,5,6])
print(np.outer(A,B))#[1*4 1*5 1*6
                      #.........
                      #          ]

[[ 4  5  6]
 [ 8 10 12]
 [12 15 18]]


In [ ]:
A=np.array([1,2,3])# + - +
B=np.array([4,5,6])#[2 3 5]
print(np.cross(A,B))

[-3  6 -3]
