In [ ]:
#variable
a=10
print("i am",a,"years old")

i am 10 years old


In [ ]:
#arthmetic of two int variables
a=int(input("enter first"))
b=int(input("enter second"))
c=(a+b)
print(c)
print(a-b)
print(a*b)
print(a/b)
print(a%b)
print(a**b)
print("floor division",a//b)

enter first20
enter second5
25
15
100
4.0
0
3200000
floor division 4


In [5]:
#take a number salary from the user.if the salaray is more than 50k there is 10% tax print his final salary
a=float(input("enter the salary:"))
if a>=50000:
    b=a*(10/100)
    print(" tax:",b)
    print("salary:",a-b)
else:
    print("no tax")

enter the salary30000
no tax


In [4]:
#get the salary from the user if the salary more than or equal 50k,apply 10% tax deduction.if the salary is less than 50k,apply 5% tax.if the salary is more than 70k,apply 12% tax.ifsalary exceeeds 1L print you are promoted to next level.
a=float(input("enter the :"))
if a>=50000 and a<70000:
    b=a*(10/100)
    print("salary:",a-b)
elif a<50000:
    b=a*(5/100)
    print("salary:",a-b)
elif a>=70000 and a<100000:
    b=a*(12/100)
    print("salary:",a-b)
elif a>=100000:
    print("you are promoted ")

enter the :100001
you are promoted 


In [ ]:
n=int(input("enter n"))
for i in range(1,n+1):
    print(i)

enter n10
1
2
3
4
5
6
7
8
9
10


In [ ]:
n=int(input("enter n"))
for i in range(1,11):
    print(n,"*",i,"=",i*n)


enter n5
5 * 1 = 5
5 * 2 = 10
5 * 3 = 15
5 * 4 = 20
5 * 5 = 25
5 * 6 = 30
5 * 7 = 35
5 * 8 = 40
5 * 9 = 45
5 * 10 = 50


In [ ]:
n=int(input("enter n"))
i=1
while(i<=10):
  print(n,"X",i,"=",i*n)
  i=i+1



enter n15
15 X 1 = 15
15 X 2 = 30
15 X 3 = 45
15 X 4 = 60
15 X 5 = 75
15 X 6 = 90
15 X 7 = 105
15 X 8 = 120
15 X 9 = 135
15 X 10 = 150


In [ ]:
#heterogeneous
l=[1,"anu",'a']
for i in l:
  print(i)


1
anu
a


In [ ]:
#mutable
l=[1,"anu",'a']
l.append(23)#adds element at back
print(l)

[1, 'anu', 'a', 23]


In [ ]:
l=[1,"anu",'a']
l.insert(2,"priya")#listname.insert(index,element)
print(l)

[1, 'anu', 'priya', 'a']


In [ ]:
l=[1,"anu",'a']
l.pop(2)#delete element using index pos
print(l)
l.remove("anu")#delete element using element
print(l)


[1, 'anu']
[1]


In [ ]:
l2=[10,"uma",'k']
l1=[1, 'anu', 'priya', 'a']
#l1.extend(l2)
print(l1+l2)#concatination of 2 lists

[1, 'anu', 'priya', 'a', 10, 'uma', 'k']


In [ ]:
l1=[1, 'anu', 'priya', 'a']
l1.clear()#listname.clear()
print(l1)

[]


In [11]:
#create a list of 10 integer elements print their squaresand save this squares in anew list
l=[2,4,6,15]
l1=[]
for i in l:
  print(i*i)




4
16
36
225


In [ ]:
#newlist=[(st of if) if (cond) else (st of else) for ]
l1=[23,67,12,36,69]
res=[i*i if i>50 else 'X' for i in l1]
print(res)

['X', 4489, 'X', 'X', 4761]


In [ ]:
l=[2,4,6,15]
rs=[i*i for i in l]
print(rs)

[4, 16, 36, 225]


In [ ]:
#take the salary from the user if the salary is less than 50k 10% tax otherwise 15% tax
l1=[30000,60000]
l=[ (i-i*(10/100)) if(i<=50000) else (i-i*(15/100)) for i in l1 ]
print(l)

[27000.0, 51000.0]


In [ ]:
#create dictionaries
dict1={"mentor":"jwalitha",1:"rohini",22:"anu",8:"uma"}
print(dict1)
print(dict1.keys())
print(dict1.values())
print(dict1[1])

{'mentor': 'jwalitha', 1: 'rohini', 22: 'anu', 8: 'uma'}
dict_keys(['mentor', 1, 22, 8])
dict_values(['jwalitha', 'rohini', 'anu', 'uma'])
rohini


In [ ]:
d={"Dept":"cse","details":{"year":2,"section":"D","strength":71}}
print(d["details"]["section"])
print("year is ",d["details"]["year"])
print("section is ",d["details"]["section"])
print("strength is ",d["details"]["strength"])


D
year is  2
section is  D
strength is  71


In [ ]:
l1=[1,2,3]
l2=["anu","uma","rohini"]
new=(zip(l1,l2))
for i in new:
  print(i)

(1, 'anu')
(2, 'uma')
(3, 'rohini')


In [ ]:
l1=[1,2,3]
l2=["anu","uma","rohini"]
new=dict(zip(l1,l2))
print(new)


{1: 'anu', 2: 'uma', 3: 'rohini'}


In [ ]:
import numpy as np
A=np.array([1,2,3,4])#1d array
print(A.ndim)
print(A.shape)


1
(4,)


In [ ]:
import numpy as np
A=np.array([[1,2,3,4],[4,5,6,7]])#2d arrray
#elements in each row=column
print(A.ndim)
print(A.shape)
print(A)



2
(2, 4)
[[1 2 3 4]
 [4 5 6 7]]


In [ ]:
import numpy as np
A=np.array([[[1,2,3,4],[8,5,6,7],[11,12,13,14]],[[1,2,3,4],[8,5,6,7],[11,12,13,14]]])#3d arrray
print(A.ndim)
print(A.shape)
print(A)

3
(2, 3, 4)
[[[ 1  2  3  4]
  [ 8  5  6  7]
  [11 12 13 14]]

 [[ 1  2  3  4]
  [ 8  5  6  7]
  [11 12 13 14]]]


In [ ]:
A=np.ones((2,2,3))#g,r,c
print(A)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


In [ ]:
A=np.zeros((2,2,3))#g,r,c
print(A)

[[[0. 0. 0.]
  [0. 0. 0.]]

 [[0. 0. 0.]
  [0. 0. 0.]]]


In [ ]:
A=np.eye(4)#identity matrix
print(A)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [ ]:
A=np.arange(1,10,2)#start,stop,step
print(A)
print(type(A))

[1 3 5 7 9]
<class 'numpy.ndarray'>


In [ ]:
#print all the numbers that are divisible by8 using arange funtn b/w 1 and 1000
A=np.arange(8,1001,8)#start,stop,step
print(A)
print(type(A))

[   8   16   24   32   40   48   56   64   72   80   88   96  104  112
  120  128  136  144  152  160  168  176  184  192  200  208  216  224
  232  240  248  256  264  272  280  288  296  304  312  320  328  336
  344  352  360  368  376  384  392  400  408  416  424  432  440  448
  456  464  472  480  488  496  504  512  520  528  536  544  552  560
  568  576  584  592  600  608  616  624  632  640  648  656  664  672
  680  688  696  704  712  720  728  736  744  752  760  768  776  784
  792  800  808  816  824  832  840  848  856  864  872  880  888  896
  904  912  920  928  936  944  952  960  968  976  984  992 1000]
<class 'numpy.ndarray'>


In [ ]:
# line space:splitting a range of num into n numbers with common differences
A=np.linspace(54,55,13)
print(A)

[54.         54.08333333 54.16666667 54.25       54.33333333 54.41666667
 54.5        54.58333333 54.66666667 54.75       54.83333333 54.91666667
 55.        ]
